### PR TITLE
76/resultpage responsiveness for mobile devices

### PR DESCRIPTION
**Pull request by DianaPankratz**

### CODE REVIEW

**Comment by FiedlerJan** [comment]
Do not merge into master. Please select staging as endpoint

**Review by MaiThiD — CHANGES_REQUESTED** [review]
Sometimes the details won't open.

image

**Review by MaiThiD — CHANGES_REQUESTED** [review]
The selected post does not close automatically when you click on another post.

**Review by MaiThiD — COMMENTED** [review]
Change the text color for the detail view in black

**Review by MaiThiD — COMMENTED** [review]
After selecting the last post on the before last page and than selecting the last page on the pagination, I am not able to select a post of the last page.

**Review by MaiThiD — COMMENTED** [review]
The pagination and footer move when I select and deselect a post (normal view).

**Review by MaiThiD — APPROVED** [review]

**Review by jonas-hda — APPROVED** [review]

**Review by LeDrieHda — APPROVED** [review]

**Pull request merged**
