### PR TITLE
244/implement the layout for integrating the search for international results

### LINKED ISSUE #244: Implement the layout for integrating the search for international results
**Reason (Why?)**
The usefulness of einander-helfen.org depends on the versatility of the results. We want to be able to offer international, as well as national, results.

**Solution (What?)**
On the home and result pages both in web and mobile view the pin icon to the left of the location search bar should be replaced by the german flag, with a small triangle next to it to indicate it being a dropdown. 
When clicking on it, a dropdown with one option "Weltweit" with a globe icon next to it should expand. 
When clicking on "Weltweit" the dropdown collapses again, the german flag icon is switched to the globe icon in the location search bar. The text inside the location search bar changes from "Ort oder PLZ" to "Land oder Kontinent", the radius field gets grayed out/disabled.  

**Out of scope**
Only the layout should be implemented here. The actual filtering of the posts/searching for international results will be implemented with another (backend) issue. 

**Relation to other Issues**
#224 
#247 implements the international search (backend).

**Acceptance criteria**
_Home page web view:_
image
image

_Result page web view:_
image
image

_Result page mobile view:_
image image

### PR DESCRIPTION
**Pull request by FiedlerJan**
Closes #244, #247 and #274.

### CODE REVIEW

**Review by DanielKraft — CHANGES_REQUESTED** [review]
If you search for a country on the start page and then go back to the start page from the ResultPage, the input field for the country is empty. But, if you now search again without further input, again only results of the previously selected country are displayed.

The reason could be that the store is not updated when reloading the start page.

**Comment by FiedlerJan** [comment]
> 
> 
> If you search for a country on the start page and then go back to the start page from the ResultPage, the input field for the country is empty. But, if you now search again without further input, again only results of the previously selected country are displayed.
> 
> The reason could be that the store is not updated when reloading the start page.

This error was already present before this issue. It occurs not only in the international version, but also in the national version. Only the Radius field gets reseted. Please create another issue for this error.

**Comment by DanielKraft** [comment]
> > If you search for a country on the start page and then go back to the start page from the ResultPage, the input field for the country is empty. But, if you now search again without further input, again only results of the previously selected country are displayed.
> > The reason could be that the store is not updated when reloading the start page.
> 
> This error was already present before this issue. It occurs not only in the international version, but also in the national version. Only the Radius field gets reseted. Please create another issue for this error.

Ok. I have created an issue: [#281 LocationSearchBar store not cleared after reload](https://github.com/hochschule-darmstadt/einander-helfen/issues/281)

**Review by DanielKraft — APPROVED** [review]

**Comment by FiedlerJan** [comment]
> 
> 
> > > If you search for a country on the start page and then go back to the start page from the ResultPage, the input field for the country is empty. But, if you now search again without further input, again only results of the previously selected country are displayed.
> > > The reason could be that the store is not updated when reloading the start page.
> > 
> > 
> > This error was already present before this issue. It occurs not only in the international version, but also in the national version. Only the Radius field gets reseted. Please create another issue for this error.
> 
> Ok. I have created an issue: [#281 LocationSearchBar store not cleared after reload](https://github.com/hochschule-darmstadt/einander-helfen/issues/281)

Right in the second you created the issue I found and fixed the bug :) 
Closes #281.

**Review by AndreBruecke — APPROVED** [review]

**Review by DanielKraft — APPROVED** [review]

**Review by MaiThiD — APPROVED** [review]

**Pull request merged**
