### PR TITLE
landing page image carousel fix

### PR DESCRIPTION
**Pull request by Alltagsheld**
The images inside the carousel component were still dragable, which lead to issues with the component. This has been removed.
Also the cursor was changed to pointer to suggest interaction by the user.

### CODE REVIEW

**Comment by theErikss0n** [comment]
The issue template was not filled out and the description of this PR is vague so i don't know what exactly should be accomplished.

As far as i understand this PR wants to make the carousel not to be draggable anymore? If so, this is not the case. The carousel is still draggable.

The pointer is a nice touch, but otherwise i don't see how the draggable issue is adressed.

Please clarify what this PR does and why we need it.

**Comment by Alltagsheld** [comment]
@theErikss0n 
sadly i cant find any option to fill out the template rn.
And you also didn't understand what happened, probably thanks to me and the missing template.
The images INSIDE the carousel were still draggable which lead to the caroussel not being able to drag properly. This has been removed.

**Review by theErikss0n — CHANGES_REQUESTED** [review]
Seems like this is only fixed in chrome. When i try this with firefox this issue remains.

Please confirm with firefox and resolve the issue if you can reproduce.

**Comment by Alltagsheld** [comment]
works now on firefox as well as chrome and edge.

**Comment by theErikss0n** [comment]
Works good now. Good job

**Review by theErikss0n — APPROVED** [review]

**Pull request merged**
