### PR TITLE
Issue/136/about page enhancement

### LINKED ISSUE #136: About page should be grammatically correct and a new paragraph should be added
**Reason (Why?)**
The content of the about page should be grammatically correct.

**Solution (What?)**
Change the following part in the first row of "einander-helfen.org":  
"...und ehrenamtliche Tätigkeiten: mit eine..."  to 
"...und ehrenamtliche Tätigkeiten: **Mit** eine..."

Change the following part in "Wer wir sind":
"Wer wir sind: Wir sind **selbst** ein ehrenamtliches Team … " to
"Wer wir sind: Wir sind ein ehrenamtliches Team …" 

Adding new paragraph (in "Wer wir sind") with the following text:
**THIS WILL BE ADDED LATER**

**Not doing**
Implementing "Über uns".

**Relation to other Issues**
#46 

**Acceptance criteria**
The text has been corrected.

### PR DESCRIPTION
**Pull request by andresesam**
In addition to the issue I have changed the styling a little bit, now it looks better than the original vanilla html and is responsive(This does not apply to the search bar)

about

Close #136

### CODE REVIEW

**Comment by andresesam** [comment]
> Imo the font is now too small, especially for old people and people with bad vision (a11y). The styling also doesnt mesh well with the other "side" pages (imprint and privacy) anymore (aligning, font size etc.). That could be done in a seperate issue though, so i would undo the styling of the about page to still the styling of those two other pages

Hi @BaderChouaib , of course you can argue about the font size. Currently, the default value of the vue card components is used and I find this easy to read. You also have to consider that this is "only" the About page and has no functionality.To remove the working responsive styling, just because the imprint page is not responsive and consists of pure HTML (and so doesn't match to this site) I find a very weak argument. Why don't you just append the styling for the imprint page?

**Comment by BaderChouaib** [comment]
I would approve these changes, despite not being part of the issue, if you apply them to the imprint page and the privacy page, while increasing the font size. Alternatively you can undo the styling changes and create an issue that deals with styling those three pages

**Comment by andresesam** [comment]
> I would approve these changes, despite not being part of the issue, if you apply them to the imprint page and the privacy page, while increasing the font size. Alternatively you can undo the styling changes and create an issue that deals with styling those three pages

Why so complicated approve it and open two issues for the other two pages... Or what is the opinion of the others? @MaiThiD @FiedlerJan

**Comment by MaiThiD** [comment]
> > I would approve these changes, despite not being part of the issue, if you apply them to the imprint page and the privacy page, while increasing the font size. Alternatively you can undo the styling changes and create an issue that deals with styling those three pages
> 
> Why so complicated approve it and open two issues for the other two pages... Or what is the opinion of the others? @MaiThiD @FiedlerJan

"Alternatively you can undo the styling changes and create an issue that deals with styling those three pages"
I would agree with @BaderChouaib .

And @andresesam you should replace the text "THIS WILL BE ADDED LATER" with https://github.com/hochschule-darmstadt/einander-helfen/issues/136#issuecomment-653128460

**Comment by andresesam** [comment]
Okay, fine, have it your way.

**Comment by BernhardHumm** [comment]
There are still some errors in the text:

1.       “aktuell werden folgende Anbieter abgedeckt:“ Entry „ehrenamtsuche-hessen“ missing. 

2.       „Weitere Anbieter folgen. “ <br> missing

3.       Delete „THIS WILL BE ADDED LATER”

 

 

 

------------------------------------

 

 

Von: andresesam [mailto:notifications@github.com] 
Gesendet: Samstag, 4. Juli 2020 15:03
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Issue/136/about page enhancement (#140)

 

In addition to the issue I have changed the styling a little bit, now it looks better than the original vanilla html and is responsive(This does not apply to the search bar)

 <https://user-images.githubusercontent.com/39090774/86513032-42069e80-be07-11ea-9b9b-eecc2c13d74b.png> 

Close #136 <https://github.com/hochschule-darmstadt/einander-helfen/issues/136> 

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/hochschule-darmstadt/einander-helfen/pull/140


Commit Summary


*	Added required content
*	Add some styling


File Changes


*	M app/src/views/About.vue <https://github.com/hochschule-darmstadt/einander-helfen/pull/140/files#diff-9c8a256daa9f4fbd989bc1fecd2962ef>  (73) 


Patch Links:


*	https://github.com/hochschule-darmstadt/einander-helfen/pull/140.patch
*	https://github.com/hochschule-darmstadt/einander-helfen/pull/140.diff

**Pull request merged**
