### PR TITLE
Issue/132/links in new tab

### PR DESCRIPTION
**Pull request by BaderChouaib**
Aims to solve #132 by modifying the DOM

### CODE REVIEW

**Comment by jschurse** [comment]
@mxxbe I really don't think the client is where we want to do such transformations. What do you think?

**Comment by jschurse** [comment]
@marvinseith @JamieArmstrongArndt how much work would it be for you to implement this in the ETL process?

**Comment by marvinseith** [comment]
should be no big of a deal, will get right to it

**Comment by marvinseith** [comment]
We would fix this for the crawled link under the 'organization' entry, since we are already manipulating the link to match the 'ehrenatmssuche-hessen' internal link. Every other link probably needs to be handled by the frontend.

**Comment by BaderChouaib** [comment]
Im not sure if doing this only for organization while the other links are being handled by the frontend would be a good approach. Imo, modification links for the fields task, contact and organization should be handled completely from the backend or the frontend. Mixing responsibilities like that would just cause confusion and drifts

**Comment by marvinseith** [comment]
Like I stated above, the links of contact and organization are getting fixed by us. Are there any links in the field task?

**Comment by BaderChouaib** [comment]
I thought ive seen posts with links in the task field, but i cant find them anymore. I think however doing this for every field with the default behaviour being that if no link exists you dont do anything would be a good approach. Especially considering that if the crawling range gets expanded (not just ehrenamtssuche-hessen) links might be in yet unexpected fields. Or does that increase the processing time in the ETL process by too much?

**Comment by marvinseith** [comment]
Since we are doing a unique crawling and unique enhancement for every domain, it only affects the ehrenatmsuche-hessen right now. Nevertheless we can do a check for links in the task section also.

**Comment by BaderChouaib** [comment]
Closing this then

**Pull request closed without merging**
