### PR TITLE
Added message for empty resultset

### PR DESCRIPTION
**Pull request by jschurse**
+ Added message for empty resultset
+ Added message for when the radius has been extended

### CODE REVIEW

**Comment by andresesam** [comment]
I like the idea with the snack bar as notification 👍

**Comment by FiedlerJan** [comment]
>     * Added message for when the radius has been extended

Do you have example data I can test with?

**Comment by FiedlerJan** [comment]
Another question I have is: If it is not within my radius, should the radius not be increased to "everywhere"?

**Comment by jschurse** [comment]
> Do you have example data I can test with?

Jugendarbeit
Darmstadt
5km
http://localhost:8080/posts?q=Jugendarbeit&location=64283%20Darmstadt%20%28alle%29&radius=5km&page=1

**Comment by jschurse** [comment]
> Another question I have is: If it is not within my radius, should the radius not be increased to "everywhere"?


`There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors.`

Yes, there was a +/- 1 Error

**Comment by jschurse** [comment]
> The message says: "Auch eine Vergrößerung des Radius liefert keine Ergebnisse." But I got 13 result with "Überall".

This should indicate that we already tried bigger radii and also did not get any results. Otherwise the user could be irritated that when his search for a 5km radius did not yield any results the radius gets extended to 'Überall'

I will remove the message.

**Comment by jschurse** [comment]
I did reword the message to 
`Zu Ihrer Suchanfrage mit einem Radius von 5km haben wir keine Treffer gefunden. Wir haben daher den Radius vergrößert, bis Ergebnisse gefunden wurden.`
when radius did get increased to 'Überall'

I also could reproduce your bug and fix it.

**Pull request merged**
