### PR TITLE
173/optimize the result page header

### PR DESCRIPTION
**Pull request by LeDrieHda**

### CODE REVIEW

**Review by MaiThiD — CHANGES_REQUESTED** [review]
The position of the logo and the burger menu do not match the position on the homepage. Also you are not able to see the dropdown menu values of the searchbar, locationsearchbar and the radius. 
image

image

**Review by FiedlerJan — COMMENTED** [review]
Please merge staging into this branch. Staging has an updated version of the npm dependencies  because the existing dependencies caused bugs. After the merge execute the following commands.

```
$ cd (einander-helfen)/app
$ rm -rf node_modules         (-rf is not working on windows, just delete the whole node_modules directory)
$ rm package-lock.json
$ npm cache verify
$ npm i
```

**Review by MaiThiD — CHANGES_REQUESTED** [review]
The location suggestions are now in the wrong position on the homepage.
image

**Review by MaiThiD — CHANGES_REQUESTED** [review]
The layout is no longer uniform.
Before:
image
image



After:

image
image

Also after selecting the locationsearchbar on the resultpage, the header is still "moving" (mobile view).

**Review by FiedlerJan — APPROVED** [review]

**Review by MaiThiD — APPROVED** [review]

**Pull request merged**
