### PR TITLE
#298/searchcomponent

### LINKED ISSUE #276: Searchbar on result page and dots of carousel on home page are asymmetric
**Describe the bug**
On the result page in web layout and mobile layout the lower corners of the search bar are shaped differently than the upper corners. In tablet layout (between 600px and 959px) the search bar is symmetric (see screenshots below).
Also the three dots below the picture carousel on the home page are not in the middle of the page, but rather slightly to the right.

**To Reproduce**
Steps to reproduce the behavior of searchbar:
1. Go to result page
2. Adjust window size to max. 599px or min. 960px width
3. See error of search bar

Steps to reproduce the behavior of dots:
1. Go to home page
2. See error of dots

**Expected behavior**
The searchbar should be symmetrical, like it is in the tablet layout, but in all window sizes.
The three dots below the picture carousel should be centered.

**Screenshots**
_Search bar web view:_
image
_Search bar in mobile view:_
image

_For comparison: search bar in tablet view is symmetrical_
image

_Three dots slightly to the right_
image

**Desktop:**
- all

**Smartphone:**
- all

### LINKED ISSUE #298: SearchComponent
**Problem**
The Search bevior is currently implemented at different locations in the code (e.g. in Header.vue, Home.Vue, different stores and all ui compontents). To get an overview of the current state of the search bevior is very difficult, because there are so many components involved in this. Furthermore, some search behavior is implemented multiple times. 

**Solution (What?)**
Create on SearchComponent and remove the search bevior from Home.vue and Header.vue. Remove the store actions from /ui/** components and make then less difficult and more understandable. Only the SearchComponent should work with the store and the components who need this information to show the results. 

**Out of scope**
Anything that is out of scope and shall not be implemented

**Relation to other Issues**
#286 

**Acceptance criteria**
The store isn't involved in any /ui/** components.   
One SearchComponent is created and used by Home.vue and Header.vue.  
Home.vue and Header.vue does't implement any search behavior.

### PR DESCRIPTION
**Pull request by xcaverxiii**
* combine search implementation from Header.vue and Home.vue in SearchComponent.vue
* reduce store interaction by abstraction from simple ui components
* make some css scoped
* combine store module files into one module file
* refactor some components 

close #298 

* fix #276 Searchbar on result page and dots of carousel on home page are asymmetric

### CODE REVIEW

**Comment by theErikss0n** [comment]
We should split this PR into smaller ones, so it is easier to see what exactly happened.
I suggest splitting it according to the sub-points in the PR-Comment
E.g: One PR for making css-scoped, another for changes to the store, etc.
So that we only have changes regarding the search-component in this PR

**Review by DianaPankratz — CHANGES_REQUESTED** [review]
* Dont't commit TODO comments (see app/src/store/store.ts line 12). If you want to add a TODO create a new Issue or take care of it before requesting a PR.
* Some responsive design stylings are broken. Check out "Home" and modify your your window size. Sometimes the search button is jumping up and down (eg with window width 600-550px). It's the same with the searchbar on the ResultPage
* On the ResultPage if you reduce the window width the burger menu slides down

**Review by DianaPankratz — CHANGES_REQUESTED** [review]
* On Home if you type something like "Ber" and choose one of the suggested locations by pressing Enter the search will start immediately. The normal behaviour should be: if you choose a suggestion with Enter the suggestion should be displayed in the location search bar but the search won't start yet. It should only start if you press enter again.
* There are still some problems with the responsive design: 
  * Home: 
     * windowWitdh ~470-370px and 330-310px: The search button an the "Umkreis" field are on the first line again but they should stay on the second line
     * windowWidth ~540px: The search button jumps to the next line but the "Umkreis" field jumps to the next line a few pixels later (This bug already exists on our live server. Could you fix it with the other bugs?)
   * ResultPage:
      * windowWidth < 1260px: The search bar is suddenly smaller. The right edge of the search bar should allways end between the list and the map
      * windowWidth < 960px: the burger menu is still too low and destroys the widths of the search fields
* If you select a "Umkreis" e.g. 5km it does not change the results

**Review by DianaPankratz — CHANGES_REQUESTED** [review]
* If you get suggestions (e.g. a list of cities) you can choose one by pressing enter without starting the search. After pressing enter a second time the search should start. This does not work anymore. 
* The radius is still not working. If you want to do it in another PR please write this into the comments

**Comment by xcaverxiii** [comment]
> * If you get suggestions (e.g. a list of cities) you can choose one by pressing enter without starting the search. After pressing enter a second time the search should start. This does not work anymore.  

Is fixed
> * The radius is still not working. If you want to do it in another PR please write this into the comments  

Will be fixed with the refectoring of the ResultPage #291

**Review by DianaPankratz — APPROVED** [review]

**Review by theErikss0n — APPROVED** [review]

**Pull request merged**
