### PR TITLE
188/adapt the data model of existing scrapers to the new version

### LINKED ISSUE #188: Adapt the data model of existing scrapers to the new version
**Reason (Why?)**
There is a new data model (#183). This shall be used by all scrapers.

**Solution (What?)**
Modify the existing data model of the scrapers for ehrenamtssuche-hessen and gute-tat so that they correspond to the new version. Additionally, the data in the data model should be made more stable.

**Out of scope**
None

**Relation to other Issues**
#183 This is the new data model.

**Acceptance criteria**
The generated data models of the scrapers of ehrenamtssucher-hessen and gut-tat correspond to the new data model.

### PR DESCRIPTION
**Pull request by FiedlerJan**
This closes #188.

You can test it with the following commands:
```
$ cd etl
$ python (or python3)
>>> import os
>>> ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
>>> os.environ['ROOT_DIR'] = ROOT_DIR
>>> from data_extraction.scrape_data import run as run_extraction
>>> run_extraction()
(this will take some time; approx. 45 min)
```
After this you can take a look at the generated files in etl/data_extraction/data.

### CODE REVIEW

**Comment by jonas-hda** [comment]
when running this via the main.py I get `Error [ehrenamt_hessen]: {'fn': 'parse', 'body': "Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?", 'index': 86, 'url': 'https://www.ehrenamtssuche-hessen.de/index.cfm?searchTab=job_entry_detail&jobEntryId=122597424&searchLocationId=0&searchDistance=0&searchSectorIds=&searchSearchterm=&backLink=%3Fparam%26searchTab%3Dentries%26countyId%3D26%26locationId%3D426'}` for every crawled post on ehrenamt_hessen it seems

**Comment by FiedlerJan** [comment]
Added they missing library to the requirements.txt. Please reinstall he requirements.

**Review by MaiThiD — COMMENTED** [review]
"We have decided to leave out logos. So:

1. Remove from data model
2. Do not set in backend"

**Review by MaiThiD — COMMENTED** [review]
when running this via the main.py I get Error [ehrenamt_hessen]: {'fn': 'parse', 'body': "'NoneType' object has no attribute 'find'", 'index': 1500, 'url': 'https://www.ehrenamtssuche-hessen.de/index.cfm?searchTab=donation_entry_detail&donationEntryId=256&searchLocationId=0&searchDistance=0&searchSectorIds=&searchSearchterm=&backLink=%3Fparam%26searchTab%3Dentries%26countyId%3D25%26locationId%3D425'}

**Comment by FiedlerJan** [comment]
> when running this via the main.py I get
> image

The error is fixed. Now another error occurs that len() cannot be applied to None. But I cannot explain this behaviour, because I check the value for None before.

**Review by MaiThiD — COMMENTED** [review]
Another error has occured:

image

**Review by MaiThiD — APPROVED** [review]

**Review by jonas-hda — APPROVED** [review]

**Pull request merged**
