### PR TITLE
#64 Updated empty query and label

### PR DESCRIPTION
**Pull request by FiedlerJan**
Added #64.

### CODE REVIEW

**Comment by BaderChouaib** [comment]
When typing sth. into the location searchbar and losing focus, the field gets cleared. After refocusing the field the location searchbar tries to autocomplete against the cleared input. You should either reset the searchValue on lost focus or just ensure that it doesnt get cleared after losing focus (imo preferred considering inexperienced user could get alienated by that behaviour)
grafik

**Comment by BaderChouaib** [comment]
Seems to work better now.
Is there a way to hide these autosuggest arrows on no-data state? Because they are not doing anything
grafik

**Comment by BaderChouaib** [comment]
You can also force autosuggestion on empty input if you previously inputted sth. then deleted the inputted manually leaving the field empty again.  
grafik
Not sure if we should regard this as a feature or complettely prevent any autosuggestion if there is no input

**Comment by FiedlerJan** [comment]
> You can also force autosuggestion on empty input if you previously inputted sth. then deleted the inputted manually leaving the field empty again.

I'm not able to reproduce this bug. Can you give a more detailed guide with sample data, please.

**Comment by BaderChouaib** [comment]
Nvm, apparently i switched branches inbetween (visible by looking at the label ob the searchbar "Standort")

**Comment by FiedlerJan** [comment]
> 
> 
> There is visual bug now when inputting a location, routing to resultPage then coming back to home. This is what you will see:
> grafik
> The arrow is back. When focusing the location searchbar the arrow hides again. Might be because showLocations does not update on page render? Its more likely that component does not notice that showLocations was being cleared. Refresh on $nextTick might help

I am unable to find a working solution to this bug. If someone finds a working solution, let me know.

**Comment by BaderChouaib** [comment]
I dont have one either. The issue seems related to this solution: 
https://github.com/hochschule-darmstadt/einander-helfen/pull/109/commits/4bcabdf80937d130e0576de404ba63e61f3fa74a
Background: This fixed the "searchbar is still not empty" issue where searchbar didnt reset the inputted text when a tag was selected. Instead of clearing input you could try to refresh ui state of the component

**Comment by BaderChouaib** [comment]
nice 👍

**Pull request merged**
